site_name: Britive Python SDK Documentation
nav:
  # rest of the navigation...
  # defer to gen-files + literate-nav
  - Code Reference: reference/  #
  # rest of the navigation...
theme: readthedocs
repo_url: https://github.com/britive/python-sdk
edit_uri: ''
copyright: 2022 Britive, Inc.
plugins:
  - search
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: false
            show_root_heading: false

